### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by mediter**
Moved Source Codes to Sources folder for LaunchAtLogin and LaunchAtLoginHelper, add Package.swift manifest

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/LaunchAtLogin/pull/25#issuecomment-528009153

**Comment by mediter** [comment]
> See [#25 (comment)](https://github.com/sindresorhus/LaunchAtLogin/pull/25#issuecomment-528009153)

Thank you for the heads-up

**Comment by sindresorhus** [comment]
> One question: judging from another repo 'Defaults", we no longer need the xcodeproj file, right?

It's needed for Carthage, I think.

**Comment by sindresorhus** [comment]
Bump

**Comment by sindresorhus** [comment]
@mediter Bump :)

**Pull request closed without merging**
